### ISSUE TITLE
Can't select Transliterated text from Suggestion.

### ISSUE THREAD

**Issue by shathish-vsk** [craftyclicks/magento2#10]
## Environment:
Magento 2.1.4 EE 
Craftyclicks_Clicktoaddress (ver: 1.1.1)

## Steps to reproduce:

1.	Set "Transliterate for non ASCII characters" to "Yes" under Store -> Configuration -> CRAFTY CLICKS -> Click to Address -> Advanced in the admin panel.
2.	In the frontend go to checkout and try to search for an address (600028: India postal code in our case).
3.	Click through multiple levels of suggestions

## Expected Result:

When selecting the last suggestion, the address should be auto-filled in the checkout address form.

## Actual Result:

The following Notice is thrown when trying to select the address suggestion:

"CraftyClicks Debug Error Message: [JS503] API address retrieve request resulted in a JS error."

![image](https://user-images.githubusercontent.com/16379101/36102301-f246337c-1031-11e8-80ea-14d6db82869a.png)

## Points to be noted:

1.	When "Transliterate for non ASCII characters" is set to "No", all work fine.
2.	First two levels of suggestion are selectable, only the last level throws the above error.
3.	JS minification and merge are enabled in Magento.

**Comment by gs-mancs** [comment]
Thanks for reporting this issue.
We identified this to be a problem with our underlying clicktoaddress-js library.
The latest pushed commit on master (v1.1.2) has been now fully tested and resolves this issue.

Do let us know if you still see any issues around transliteration.

**Comment by shathish-vsk** [comment]
Thanks,

It works now after the update. Hence closing the issue.
