### ISSUE TITLE
System.xml type issue. 

### ISSUE THREAD

**Issue by IvanDotsenko** [craftyclicks/magento2#11]
In the etc/admin/system.xml file should be type="obscure" for field "accesstoken" now it is type="text", 

`<field id="accesstoken" type="text" sortOrder="2" showInDefault="1">
					<label>Access Token</label>
					<backend_model>Magento\Config\Model\Config\Backend\Encrypted</backend_model>
				</field>` 

https://github.com/craftyclicks/magento2/blob/master/etc/adminhtml/system.xml#L17:L20

**Comment by gs-mancs** [comment]
Could you perhaps mention why would this be a good idea?
I don't really see any benefits of not being able to see your own public access token.
