### ISSUE TITLE
Unable to add custom classes to input

### ISSUE THREAD

**Issue by adam-paterson** [craftyclicks/magento2#13]
At the moment I don't think it's possible to use a mixin to amend the postcode field rendered by [cc_default_checkout.js](https://github.com/craftyclicks/magento2/blob/master/view/frontend/web/form_integrations/cc_default_checkout.js).

Could somebody advise the best approach here?

**Comment by gs-mancs** [comment]
Hi there,

This plugin doesn't really touch the postcode field at all.
Our other extension is more about postcode fields and such:
https://github.com/craftyclicks/magento2-ukpostcodelookup

But even that extension currently doesn't support adding classes to the postcode field.

These extension do not insert new elements (such as a postcode field) so if you wish to add a class to such an element, you can apply it directly to the checkout template.

**Comment by adam-paterson** [comment]
@GaborSuranyi Apologies, moment of stupidity after a long day.
