### ISSUE TITLE
Clicktoaddress sometimes doesn't change country at guest checkout

### ISSUE THREAD

**Issue by JacobDrummond** [craftyclicks/magento2#15]
### Environment
* Magento CE 2.3.1
* Luma theme
* Craftyclicks_Clicktoaddress 1.1.8

### Replication steps
1. Set default shipping country to "United Kingdom"
1. Add a product to cart
1. Go to guest checkout
1. In "Address Search" field click "Change Country"
1. Select Spain
1. Search for an address so that the results show a list of addresses, as oppposed to the region/city tree structure.
1. Click an address

### Expected result
* Magento's address fields are populated. The country `<select>` changes from default country (UK) to CraftyClicks country (Spain)

### Actual result
* Most address fields are populated by CraftyClicks
* Country `<select>` remains unchanged. The Spanish postcode fails UK postcode validation.
* (If you navigate through region/city results, then click an address, the Magento country field _does_ update). This bug relates to address top-level results.

**Comment by paulmaxwell** [comment]
@JacobDrummond 

Thanks for reporting this issue. I did some testing on a fresh Magento installation but was unable to reproduce the problem.

Are you using a custom checkout extension?

Does it happen with particular searches? If so, can you share the problem address and/or create a screencast of the problem?

Is this on a live website we can access for debugging?

Thanks,
Paul

**Comment by paulmaxwell** [comment]
@JacobDrummond

Thanks for reporting this issue. I did some testing on a fresh Magento installation but was unable to reproduce the problem.

Are you using a custom checkout extension?

Does it happen with particular searches? If so, can you share the problem address and/or create a screencast of the problem?

Is this on a live website we can access for debugging?

Thanks,
Paul

**Comment by JacobDrummond** [comment]
We cannot replicate this on the live site (Magento 2.2.3). We can replicate it on the Staging site (Magento 2.3.1). What's the best way of privately sending you the Staging URL?

**Comment by paulmaxwell** [comment]
You can contact us using the live chat on our website or email support@craftyclicks.co.uk to open a ticket.
