### ISSUE TITLE
Uncaught Already initiated

### ISSUE THREAD

**Issue by kerlama** [craftyclicks/magento2#16]
Hi,

on the magento 2.3.5-p1 and mageplaza one step checkout (latest) and your latest module, I am getting:

Uncaught Already initiated

Any hints ?

**Comment by gs-mancs** [comment]
Hi @kerlama 
Can you please provide a link to a store where we can take a look at this issue?
You can get in touch with our support team directly at support@fetchify.com.

**Comment by kerlama** [comment]
Check your email ...

**Comment by kestraly** [comment]
Did they ever resolve this one?

EDIT: Figured it out
Add Fetchify_Fetchify/layout/onestepcheckout_index_index.xml 
To your template directory
```
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	  xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
	<head>
		<script src="Fetchify_Fetchify::form_integrations/cc_default_checkout.js"/>
		<remove src="Fetchify_Fetchify::form_integrations/cc_aheadworks_checkout.js"/>
	</head>
</page>
```

Add the standard and remove the aheadworks checkout
