### ISSUE TITLE
Search in new addess popup not working

### ISSUE THREAD

**Issue by kerlama** [craftyclicks/magento2#19]
Hi,
one of our client's is using mageplaza one step checkout and now we upgraded both checkout module and craftyclicks to fetchify, and now when you are logged in and want to add new address on checkout, address lookup not working:

http://prntscr.com/1258t1w

As you can see, place holder is rendered but nothing happens when you start typing the address. But if you are guest or new customer, lookup is working on fine on checkout page itself.

No js issues in console.

Magento is 2.4.2 and latest fetchify module.

Thanks

**Comment by Jack-Fetchify** [comment]
Hi

Can we ask you to open a ticket with us directly rather than discuss here on GitHub? Please email support@fetchify.com

When you open the ticket, please provide a store URL or the mageplaza module itself. A URL is preferable (at least at first).

Thanks
Jack
