### ISSUE TITLE
Bug with Access Token

### ISSUE THREAD

**Issue by faradey** [craftyclicks/magento2#20]
Hello!
Please, rewrite the code from
```
<field id="accesstoken" type="text" sortOrder="1" showInDefault="1" showInWebsite="1" showInStore="1">
					<label>Access Token</label>
					<backend_model>Magento\Config\Model\Config\Backend\Encrypted</backend_model>
					<validate>token-format</validate>
				</field>
```

to 
```
<field id="accesstoken" type="obscure" sortOrder="1" showInDefault="1" showInWebsite="1" showInStore="1">
					<label>Access Token</label>
					<backend_model>Magento\Config\Model\Config\Backend\Encrypted</backend_model>
					<validate>token-format</validate>
				</field>
```

Namely, type text to type obscure.
Otherwise, the module does not work for Magento 2.4.3.

**Comment by Ashwin-Fetchify** [comment]
Hi @faradey,

Thanks for raising this issue.

We found no issues installing, configuring and utilising our plugin on a fresh Magento 2.4.3 installation.

It could be that another plugin is conflicting with ours, e.g. a one-page checkout plugin.

Thanks,
Ashwin

**Comment by faradey** [comment]
When do you use
`<backend_model> Magento \ Config \ Model \ Config \ Backend \ Encrypted </backend_model>`
should indicate
`type = "obscure"`
and you have specified
`type = "text"`
This is a minor bug, but it prevents the token from being saved normally in the settings. I ask you to fix it in the next versions of the module

**Comment by Jack-Fetchify** [comment]
@faradey Are you trying to encrypt the backend HTML? If so can you explain why, since only the admin can see the token in plain text?
