### ISSUE TITLE
JS error (clickToAddress.attach) when adding customer address in admin

### ISSUE THREAD

**Issue by helloeverything** [craftyclicks/magento2#30]
When adding a new customer address in the admin, I get a JS error (Uncaught TypeError: Cannot read properties of undefined (reading 'getAttribute') at clickToAddress.attach).

Using version 2.4.1 on magento 2.4.3-p3

**To replicate**
In the admin go to 
Customers > All Customers > Select existing
Click Addresses tab > Add new address
Inspect console

<img width="966" alt="Screenshot 2022-11-29 at 15 08 23" src="https://user-images.githubusercontent.com/678701/204574080-15adfb59-8d75-4c2c-82b2-f96d741a2ca9.png">

**Comment by BenButterfield** [comment]
I see the exact same issue: https://gyazo.com/609e9e8a94a7fe8f0763e3f549ad762f

I am using fetchify/module-fetchify v2.4.1 with Magento 2.4.5-p1.

**Comment by PaulWatt** [comment]
I see the same error.
Any news on this?

**Comment by Ashwin-Fetchify** [comment]
This has been fixed in https://github.com/fetchify-dev/magento2/pull/32. 

Thanks for raising this issue!
